# action.yml
name: 'Textile Bucket Remove'
description: 'Remove a Textile Bucket with CI'
inputs:
  bucket-name:  # name of bucket in your project
    description: 'Name of Bucket to remove'
    required: true
  token:  # admin auth token for textile
    description: 'Auth token from $HOME/.textile/auth.yml'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.bucket-name }}
    - ${{ inputs.token }}