name: bucket_push
on:
  pull_request:
    branches:
      - master

jobs:
  bucket_push:
    runs-on: ubuntu-latest
    name: Remove a Textile Bucket
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Get the Bucket URL
      run: echo "bucket-remove-action-${{ github.event.pull_request.head.sha }}"